spring:
  datasource:
    url: jdbc:mysql://101.34.45.254:3306/homework?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: nightcity
mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 1011